# Generated by Django 3.1.3 on 2021-08-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.CharField(max_length=225)),
                ('value_one', models.IntegerField()),
                ('question_two', models.CharField(max_length=225)),
                ('value_two', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pool')),
            ],
        ),
    ]
