# Generated by Django 3.1.3 on 2021-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='question_one',
            new_name='option_one',
        ),
        migrations.RenameField(
            model_name='pool',
            old_name='question_two',
            new_name='option_two',
        ),
        migrations.AddField(
            model_name='pool',
            name='quesstion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
