# Generated by Django 3.1.3 on 2021-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210823_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='value_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='value_two',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
